scripts/curl_install/install, scripts/curl_install/install.py, src/common_modules/vsts-cli-common/vsts/cli/common/_credentials.py
1. Avoid creating the executable script if one already got created (because of pip install vsts-cli)
2. Simplify the wording of prompts
3. Be more clear about what we did and how to run the CLI after install
This partially addresses issue #77, but there is still additional logic needed to handle the case where pip install places "vsts" in the /usr/local/bin (or other existing $PATH directory). When this happens, we don't need to try adding the install directory to the $PATH or creating an executable.
=> Simplify install script

src/common_modules/vsts-cli-common/vsts/cli/common/services.py
Improve error message when --project is not specified but required by telling the user how to configure the default (similar to the error about --instance)
=> Improve error message when --project is not specified but required by telling the user how to configure default (similar to --instance error message)

src/command_modules/vsts-cli-package/vsts/cli/package/arguments.py
Arguments to the upack commands are passed straight through to ArtifactTool. This results in a confusing user experience when arguments are empty, as error messages will reference the ArtifactTool parameter names, not the vsts-cli parameter names.
This PR sets the 'type' of the arguments (really just an arbitrary callable to transform the argument) to a function that enforces that the value is non empty.
I also removed the options_list values because they were simply restating the default.
I also changed package_name and package_version to name and version because those were wrong.
This produces a nice error message like 
```
usage: vsts package upack publish [-h] [--verbose] [--debug]
[--output {json,jsonc,table,tsv}]
[--query JMESPATH] --instance TEAM_INSTANCE
--feed FEED --name NAME …
```
=> Require that required arguments to upack commands are not empty

scripts/docgen/conf.py, scripts/docgen/doc_source_map.json, scripts/docgen/extensions/vsts.py
Mitch Denny got the following error when trying to run the doc gen tool:
```
Exception occurred:
File "C:\Code\vsts-cli\scripts\env\lib\site-packages\knack\parser.py", line 88, in load_command_table
cmd_tbl = command_loader.command_table
AttributeError: 'dict' object has no attribute 'command_table'
```
Something changed in Knack which caused this to no longer work. This PR syncs key parts from the latest AZ CLI script into the VSTS CLI script.
=> Fix docgen

src/common_modules/vsts-cli-work-common/vsts/cli/work/common/work_item.py
Currently 'get_work_items' API takes upto 200 work item IDs at a time. 
Hence limiting the batch size to 200. (Total upto 1000 work items would be displayed)
=> Adding work items batch query limit as 200

Dockerfile, src/common_modules/vsts-cli-common/vsts/cli/common/_credentials.py, src/common_modules/vsts-cli-common/vsts/cli/tests/test_credentials.py
Since, keyrings.alt package is  less secure, removing dependency on keyrings.alt package and storing credentials in file when keyring is missing.
This is done to support some linux distributions where keyring is not available.
A personalAccessTokens file will be created at path $HOME/.vsts/cli , which will be used to store the PAT tokens
Also fixing service url to include organization name for new azure devops URLs
=> Removing keyrings.alt and fixing urls for rebranding change

azure-devops/azext_devops/dev/team/arguments.py
Changing argument name from default '--open-browser' to '--open'
=> Fixing open browser argument for devops project context

azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/dev/common/telemetry.py, azure-devops/azext_devops/test/boards/test_workitem.py, azure-devops/azext_devops/test/common/test_services.py, azure-devops/azext_devops/test/common/test_telemetry.py, azure-devops/azext_devops/test/repos/test_pull_request.py
1. Add support for logging shell type in CI (code from azure cli)
1. Fix issue in vss_Connection cache - case mismatch was resulting in cache miss
1. Telemetry is getting logged in UTs (needs to be fixed - get_vss_connection call should not be made in UTs), this PR handles not to log the telemetry
1. Added tests
=> Telemetry related fixes

azure-devops/azext_devops/dev/team/credentials.py
An organization with public projects enabled will not throw any exception for invalid token. Hence, handling anonymous user case here in login command.
=> Fixing error message for login with invalid token

tests/utilities/helper.py
Recorded tests are not being called inside wrapper function.
=> Fixing recorded tests

azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/test/team/test_service_endpoint.py
[This](https://github.com/Azure/azure-cli/blob/beb3ccf7a555db7ec108862d011de5cb51f045c0/src/command_modules/azure-cli-dla/azure/cli/command_modules/dla/custom.py#L177) is how even azure CLI is doing this
This is for fixing https://github.com/Microsoft/azure-devops-cli-extension/issues/437
=> add support to pass secrets in interactive mode without params

azure-devops/azext_devops/dev/pipelines/runs.py
This is in response to the bug bash that the Protocol team just went through. This fixes the feedback about run-id, path and artifact-name not being mandatory.
=> Made run-id, path and artifact-name mandatory.

azure-devops/azext_devops/dev/common/git.py, azure-devops/azext_devops/dev/repos/commands.py, azure-devops/azext_devops/dev/repos/pull_request.py, azure-devops/azext_devops/dev/repos/ref.py
https://github.com/Microsoft/azure-devops-cli-extension/issues/249
=> Implement PR checkout

azure-devops/azext_devops/__init__.py, azure-devops/azext_devops/dev/common/telemetry.py, azure-devops/azext_devops/test/common/test_telemetry.py
Issue: https://github.com/Microsoft/azure-devops-cli-extension/issues/502
=> update to capture more in telemetry

azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/dev/team/_format.py, azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/commands.py, azure-devops/azext_devops/dev/team/wiki.py
Feature: Wiki commands #435 
Help Commands output:
Create, list, show, delete commands usage:
Command help sample (Wiki create command):
=> Adding wiki and wiki page commands for create, update, show, delete operations

azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/wiki.py
If we auto detect repository we will need to pass --repository ' ' while creating project wiki else it fails. 
With this change --repository will only need to be passed with code wiki and not project wiki.
=> Remove repo auto detect to avoid passing repository in projectwiki create

.azure-pipelines/azure-pipelines-released-version.yml
Failing pipeline url: https://dev.azure.com/ms/azure-devops-cli-extension/_build?definitionId=36&_a=summary
=> Fix agent version in release pipeline yml

azure-devops/azext_devops/dev/team/wiki.py, azure-devops/azext_devops/devops_sdk/client.py, azure-devops/azext_devops/devops_sdk/v5_0/wiki/wiki_client.py
Updating a wiki page requires the version to be given as if-match header. 
The client does not support it so adding it in the client for now.
This will need to be fixed in the Azure-Devops-python client. I will separately follow up on that.
=> Update wiki page requires if match header in the request

azure-devops/azext_devops/dev/team/wiki.py
1. Project wiki creation should not require --name as it is defaulted to project name
=> Wiki command fixes - project wiki create scenario

azure-devops/azext_devops/dev/pipelines/pipeline_create.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/github_api_helper.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/pipelines_resource_provider.py
Bug Fixes in az pipeline create command: 
1. Handle long list of service connections in pipeline create (filter the list to only connections create by the user or App connections
1. Handle github file checkin failures by raising appropriate error
=> Bug fixes : Handle long list of service connections and  Github file checkin failure  in pipeline create command

.azure-pipelines/templates/install-azure-cli-edge.yml, azure-devops/azext_devops/dev/common/config.py, azure-devops/azext_devops/dev/team/configure.py
**Issue**: Configuration read is failing and hence tests were failing since organization and project are set via config in tests
**Reason**: Breaking change: Knack has introduced the concept of scoped configurations which allows chaining of config files. For back compat they allow not using this feature.
The new setter function added in the same PR if used will handle setting the values such that they can be retrieved using the getter. PR link - https://github.com/Microsoft/knack/pull/148
**Fix:** Used the new knack setter function to be consistent in reading and writing the file using knack 
CLIConfig class functions. 
**Fix 2**:
Also making a change to not  display the value of environment variables anymore in config list command. Since it might end up displaying secrets set in …
=> Regression fix for knack config file chaining functionality

azure-devops/azext_devops/dev/team/_format.py, azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/dev/team/arguments.py
=> Add examples in Wiki Commands + minor table format edit 

azure-devops/azext_devops/dev/boards/work_item.py, azure-devops/azext_devops/dev/common/uuid.py, azure-devops/azext_devops/dev/repos/policy.py, azure-devops/azext_devops/dev/team/project.py, azure-devops/azext_devops/dev/team/team.py
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/605
=> remove UUID from help texts

azure-devops/azext_devops/dev/common/git.py, tests/test_gitAliasTest.py
In our pipeline the windows machine does not use the MSI installer hence the issue is not reproducible there. 
Just to show a test fail scenario I changed the code to alias the command as az1 instead of az and here is the pipeline failure link - https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=16747&view=ms.vss-test-web.build-test-results-tab
=> Git alias fix for windows and tests

azure-devops/azext_devops/dev/common/prompting.py
Just for reference :
https://www.geeksforgeeks.org/vulnerability-input-function-python-2-x/  
knack has same code as of now in prompt, but now fix is needed only in one place
=> use prompt instead of self defined input function

doc/samples.md
The `az devops configure --use-git-alias yes` command usage is wrong. This fixes #651
=> Update samples.md - fixing command signature

azure-devops/azext_devops/dev/team/invoke.py
=> Bug fix:Invoke command fails if content-type is none in response.

azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/dev/common/uri.py, azure-devops/azext_devops/dev/team/configure.py, azure-devops/azext_devops/test/common/test_services.py, azure-devops/azext_devops/test/team/test_configure.py
1. Handled in Configure command so ```az devops configure --default organization=abc``` fails with error 
```"Organization should be a valid Azure DevOps or TFS repository url. See command help for details."```.
1. Handled in resolve function which is called by each command so command like ```az devops project list --org abc``` will fail with error - ```"--organization must be specified. The value should be the URI of your Azure DevOps organization, for example: https://dev.azure.com/MyOrganization/ or your TFS organization. You can set a default value by running: az devops configure --defaults 'organization=https://dev.azure.com/MyOrganization/. For auto detection to work (--detect true), you must be in a local Git directory that has a "remote" referencing a Azure DevOps or TFS …
```
=> Fix invalid org name handling in configure and resolve

azure-devops/azext_devops/dev/pipelines/pipeline.py
=> Fix the pipelines run open url to open build instead of definition

azure-devops/azext_devops/dev/common/utils.py
Fix to error #716. Now if there is no default program to open yaml files it will show the program chooser
=> Open-file in editor should not fail if default editor is not set for the file type

azure-devops/azext_devops/dev/pipelines/pipeline_variables.py, azure-devops/azext_devops/dev/pipelines/variable_group.py
Azure CLI does not allow the use to specify as param as **--value ''**, in this case we make it '' for case when --value is skipped. 
Note that we cannot do that in update so in case of update the restriction will still apply that the user cannot set the value to none.
=> Allow creating pipeline variables and variable-group variables as empty strings

azure-devops/azext_devops/dev/team/commands.py, azure-devops/azext_devops/dev/team/feedback.py
- Hide command
- Deprecate message pointing to use az feedback instead.
- Do not open the url only print the message as it used to do earlier (so that the hit count on the url comes down.)
=> Deprecate feedback command

.vscode/settings.json, azure-devops/azext_devops/dev/artifacts/arguments.py, azure-devops/azext_devops/dev/artifacts/universal.py, azure-devops/azext_devops/dev/common/artifacttool.py, azure-devops/azext_devops/test/artifacts/test_univeral.py
The required change in ArtifactTool has now been released.
This adds unit tests missing in #835, so contains the changes in #835 + unit tests.  Otherwise, this PR has the same changes as #785 , which was reverted in #789 since the change in ArtifactTool wasn't ready at the time.
=> Re-adding optional project parameter to artifacts universal commands + unit tests

azure-devops/azext_devops/dev/common/credential_store.py
Fixes #762 
If keyring is not configured properly, we will store the credentials in file (in user home directory) with a warning
=> Fallback to file storage when keyring is not working

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, .azure-pipelines/templates/install-azure-cli-edge.yml, doc/samples.md
We should merge this as soon as builds turn green for this build
Revert "use python 3.7 instead of latest because 3.8 has issues (#863)"
This reverts commit a98f526d9e170bce24d07b4888faae0b0086eaaf.
=> Ideally we should be testing with latest version of python

azure-devops/azext_devops/dev/common/artifacttool_updater.py
- [ Issue #776 ] : This PR has a corresponding issue open in the Repository.
This PR is adding more logging and retry around os.rename which is failing for some customers because some other process is locking the file(may be an antivirus). There shouldn't be any retry in case of success.
=> Retrying os rename on failure and more logging

azure-devops/azext_devops/dev/common/artifacttool.py, azure-devops/azext_devops/dev/common/external_tool.py, scripts/runStyleCheck.ps1
=> Zhentan exitcode

README.md, doc/command_mapping.md, doc/getting_started.md, doc/samples.md
No code changes. Part of an effort to remove unnecessary versioning link syntax.
See user story [1797650](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1797650) for more information.
=> 1797650: Remove '?view=azure-cli-latest' syntax

azure-devops/azext_devops/dev/admin/commands.py, azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/repos/commands.py, azure-devops/azext_devops/dev/team/commands.py
Fixes #1167 
replaced the method name
=> "command" replaced by "show_command" for show

azure-devops/azext_devops/dev/repos/ref.py, azure-devops/azext_devops/test/repos/test_ref.py, tests/recordings/test_ref_createDeleteFlow.yaml, tests/test_reposRefDeleteFlowTest.py
Fixes: #1132
Made object id optional while deleting the refs (i.e. heads and tags)
Changes done: 
1. Flow:  Object id is resolved on the go and provided it to API, As Object Id is not optional in API.
2. Code: E2E test case added specifically for delete ref (Create and delete ref)
=> Fixed: Made object id optional

azure-devops/azext_devops/dev/repos/ref.py, azure-devops/azext_devops/test/repos/test_ref.py
=> Raising exception when when create ref action could not complete

tests/recordings/test_devops_group_and_member_tests.yaml, tests/test_devopsSecurityGroupTest.py
Fixes: #1174
Increased the pause time for all the commands
=> Fixed test test_devops_group_and_member_tests

tests/recordings/test_pull_request_createUpdateVoteListAbandonReactivateCompleteReviewers.yaml, tests/test_reposPrCommandsReviewersTest.py
Fixes: #1177 
Updated the organization
Updated the target project and Repo
Updated pipeline reviewer name with a permanent account
=> test_pull_request Fixed

.vscode/launch.json, azure-devops/azext_devops/dev/pipelines/arguments.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py
Edit
Fixes: #1136 
Changes:
1. Removed name property from update command As its deprecated from the API side
=> Removed name property from update command

azure-devops/azext_devops/dev/repos/pull_request.py, azure-devops/azext_devops/test/repos/test_pull_request.py
Fixes: #1118 
`reviewers = list(set(x.lower() for x in reviewers))`
using above code snippet to discard duplicate reviewer
As reviewers object is list of email Ids, it is safe to do apply `.lower()`
=> Duplicate reviewers email ids discarded

azure-devops/azext_devops/azext_metadata.json, azure-devops/azext_devops/dev/common/services.py
=> Fix broken az devops auth

azure-devops/azext_devops/dev/boards/arguments.py, azure-devops/azext_devops/dev/boards/relations.py
Fixes: #1109 
Added `--target-url` subcommand to support WI URL to add as the relation.
`--target-url` and  `--target-id` both can be added in a single command.
=> Allow setting remote related WI relations

doc/command_mapping.md
Bulk update: Edit incorrect Azure CLI reference links by removing /ext.
This work is in accordance with [User Story 1948095](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1948095).
=> Fix incorrect Azure CLI reference links

azure-devops/azext_devops/dev/common/_credentials.py, azure-devops/azext_devops/dev/common/credential_store.py, azure-devops/azext_devops/dev/team/invoke.py
The latest release pipeline run has failures for flake8:
https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=343344&view=logs&j=80f57011-57e2-5285-6819-df5013f56833&t=615f2ee2-d39f-5ed7-cc5d-f92e2c71ab0c
=> Fixes for flake8 failures in latest release pipeline results

azure-devops/azext_devops/dev/common/services.py
get_token_from_az_logins() method uses the wrong comparison when finding an active subscription from az login data. The code fails to insert active subscription as first identity without outputting any errors or warning. 
This PR fixes comparison and active subscription is added into tenantsDict as first item.
Compare with get_default_subscription_info() in same file.
=> Fixed default order of the identities

azure-devops/azext_devops/dev/pipelines/release.py
Added the parameters `--min-created-time` and `--max-created-time` to `az pipelines release list`. Approach was so simple I decided to go ahead on the PR.
=> Add `--[min/max]-created-time` to `az pipelines release list`

azure-devops/azext_devops/dev/repos/pull_request.py, azure-devops/azext_devops/test/repos/test_pull_request.py
Extends the behavior that auto-populates title when there is a single commit to also copy the entire commit comment to PR description. Resolves #695.
=> Auto-populate PR description from commit message

azure-devops/azext_devops/dev/team/wiki.py
Solves #1404.
Minor change to expose parameter that was already built into the `wiki_client`.
=> Enable use of recursion-level parameter for wiki get_page (show)

.azure-pipelines/templates/install-azure-cli-edge.yml, .github/actions/install-azure-cli-edge/action.yml
=> vulnerable fixes
