Azure/azure-devops-cli-extension

src/common_modules/vsts-cli-build-common/vsts/cli/build/common/custom.py
to resolve #92 
Similar to the way how it is done for pull requests
Note that I am not sure if I could compile it correctly locally.
=> try to auto detect branch for queue build command

scripts/windows/init.ps1
Fix capitalization of PowerShell and the cmdlet names.
=> Fix capitalization.

scripts/generate_command_inventory.py
Fixes inventory command to correctly output CLI commands and its arguments ..
```json
{
"build list": [
"definition_ids",
"branch",
"team_instance",
"project",
"detect",
"top",
"result",
"status",
"reason",
"tags",
"requested_for"
],
"build queue": [
"definition_id",
"definition_name",
"source_branch",
"open_browser",
"team_instance",
"project",
"detect"
]
}
```
=> Update command inventory command to generate JSON

src/common_modules/vsts-cli-common/setup.py
Changelog: https://github.com/jaraco/keyring/blob/master/CHANGES.rst
=> Upgrade keyring to 12.2.1

azure-devops-extension/azext_devops/dev/common/services.py, azure-devops-extension/azext_devops/dev/pipelines/_format.py, azure-devops-extension/azext_devops/dev/pipelines/_help.py, azure-devops-extension/azext_devops/dev/pipelines/arguments.py, azure-devops-extension/azext_devops/dev/pipelines/commands.py, azure-devops-extension/azext_devops/dev/pipelines/release.py, azure-devops-extension/azext_devops/dev/pipelines/release_definition.py
=> Porting release related command to extension

README.md, doc/dev_setup.md
Minor changes in readme and updating dev_setup documentation.
ToDo: Update documentation links in Readme once the repo is renamed.
=> Updating readme and dev setup doc

azure-devops/azext_devops/version.py
requirement coming from https://github.com/Azure/azure-cli-extensions/pull/450
=> change version to 0.1.0

azure-devops/azext_devops/dev/boards/commands.py, azure-devops/azext_devops/dev/repos/commands.py, azure-devops/azext_devops/dev/team/commands.py
Keyword argument 'confirmation' expects either of the following
1. True or False with default message
2. A custom confirmation message 
3. A callable function which accepts command_args as input.
Since we need custom message according to the artifact to be deleted, going with second option.
=> Fixing delete prompts

azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/project.py, azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/dev/team/team.py
covering the commands under devops in phase 1
=> Fix usage of Id to make it consistent for commands in 'az devops **'

README.md
Fixed announcement text to remove specific dates for deprecation and to be consistent with the announcement text in VSTS CLI help doc
=> Fixed annoucement

README.md, azure-devops/setup.py, azure-pipelines-merge.yml, azure-pipelines-pr.yml, doc/dev_setup.md, doc/release_new_version.md
Please make sure the code is following contribution guidelines at doc/contributing.md
skipping these for now, approach was closed internally
=> respond to branch name change

azure-pipelines-create-release.yml, azure-pipelines-merge.yml, azure-pipelines-pr.yml, azure-pipelines-released-version.yml, scripts/setupCiMachine.ps1
Please make sure the code is following contribution guidelines at doc/contributing.md
=> do not update pip in test setup

azure-devops/azext_devops/dev/team/credentials.py
- [NA] : This PR has a corresponding issue open in the Repository.
=> Fix logout help text

.azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, scripts/findAndInstallExtensionFromPath.ps1, tests/test_adminBannerTest.py, tests/test_boardsQueryTest.py, tests/test_boardsWorkItemTest.py, tests/test_devopsProjectTest.py, tests/test_devopsTeamTest.py, tests/test_pipelinesBuildDefinitionsTest.py, tests/test_pipelinesBuildTaskTest.py, tests/test_pipelinesBuildTest.py, tests/test_reposImportTest.py, tests/test_reposPrCommandsReviewersTest.py, tests/test_reposPrPoliciesWorkItemsTest.py, tests/test_reposRepoTest.py, tests/utilities/helper.py
NA : This PR has a corresponding issue open in the Repository.
NA : Approach is signed off on the issue.
This is needed so that we can make sure our recorded tests can run without our extension code (i.e. with an extension installed from azure cli extension index)
=> trying to put recording tests with wheel check in pr pipeline

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-merge.yml, .github/ISSUE_TEMPLATE/bug_report.md, azure-devops/azext_devops/version.py, doc/release_new_version.md, scripts/runTests.ps1
This is blocked on https://github.com/Azure/azure-cli-extensions/pull/483
=> bump up version to 0.3.0

scripts/setupCiMachine.ps1
- [ NA ] : This PR has a corresponding issue open in the Repository.
- [ NA ] : Approach is signed off on the issue.
=> changes to upgrade pip and not install keyring while preparing machine

azure-devops/azext_devops/dev/common/uri.py, azure-devops/azext_devops/dev/common/vsts_git_url_info.py, azure-devops/azext_devops/test/common/test_vsts_git_url_info.py
=> Support ssh url parsing in git repo auto detect

azure-devops/azext_devops/dev/repos/_help.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/commands.py, doc/command_mapping.md, examples/PRReportGeneration.ps1, tests/test_reposPoliciesTest.py, tests/test_reposPrPoliciesWorkItemsTest.py
=> udpate polices in command to policy

README.md
=> Update Build Status

tests/test_adminBannerTest.py, tests/test_reposPoliciesTest.py
=> Fix test flakiness

.azure-pipelines/azure-pipelines-merge.yml
=> fix merge pipeline

examples/PRReportGeneration.ps1
=> update in PR report generation

azure-devops/azext_devops/dev/repos/_format.py, azure-devops/azext_devops/dev/repos/_help.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/policy.py, azure-devops/azext_devops/test/repos/test_policy.py, azure-devops/setup.py
=> Group params/ arguments for policy commands and add examples

README.md
=> fix the output of `az devops -h` in readme

.azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-released-version.yml
=> fix live tests

azure-devops/azext_devops/dev/common/pip_helper.py
=> Bump up keyring version to 17.1.1

azure-devops/azext_devops/dev/repos/_help.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/commands.py, doc/command_mapping.md, scripts/utCoverage.json, tests/test_reposPrCommandsReviewersTest.py, tests/test_reposPrPoliciesWorkItemsTest.py
- NA : This PR has a corresponding issue open in the Repository.
- NA : Approach is signed off on the issue.
=> Renaming plural subgroups in repos

azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/dev/repos/import_request.py, azure-devops/azext_devops/test/common/test_services.py
Bug fix for:
https://github.com/Microsoft/azure-devops-cli-extension/issues/430
=> give proper error message in case --repository is missing

doc/getting_started.md
=> Docs: az devops configure command is incorrect

azure-devops/azext_devops/dev/admin/arguments.py, azure-devops/azext_devops/dev/admin/banner.py, azure-devops/azext_devops/dev/artifacts/arguments.py, azure-devops/azext_devops/dev/artifacts/universal.py, azure-devops/azext_devops/dev/boards/arguments.py, azure-devops/azext_devops/dev/boards/work_item.py, azure-devops/azext_devops/dev/pipelines/arguments.py, azure-devops/azext_devops/dev/pipelines/build.py, azure-devops/azext_devops/dev/pipelines/build_definition.py, azure-devops/azext_devops/dev/pipelines/release.py, azure-devops/azext_devops/dev/pipelines/release_definition.py, azure-devops/azext_devops/dev/pipelines/task.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/import_request.py, azure-devops/azext_devops/dev/repos/policy.py, azure-devops/azext_devops/dev/repos/pull_request.py, azure-devops/azext_devops/dev/repos/repository.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/credentials.py, azure-devops/azext_devops/dev/team/project.py, azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/dev/team/team.py
=> trim how we are using same help text over and over again

azure-devops/azext_devops/vstsCompressed/work_item_tracking_process_template/v4_1/models/__init__.py
=> Fix bad import

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-released-version.yml
=> Update release script and post release test script

.azure-pipelines/azure-pipelines-create-release.yml
=> Minor fix in release creation

.azure-pipelines/templates/setup-ci-machine.yml, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/policy.py
also install wheel 0.30.0 because azure cli will not support extensions created with wheel about 0.30.0
=> some help text fixes

.azure-pipelines/azure-pipelines-merge.yml, .github/ISSUE_TEMPLATE/bug_report.md, azure-devops/azext_devops/version.py
=> update extension version to 0.4.0

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> fix python version in windows machines

tests/recordings/test_repos_policies_createUpdateShowListDelete.yaml, tests/test_reposPoliciesTest.py
=> recorded tests for policy command

.azure-pipelines/azure-pipelines-create-release.yml
=> Draft release created on Github via Azure Pipelines should have pre-release flag as false

azure-devops/azext_devops/test/repos/test_ref.py
This changeset introduce more unit tests covering the `ref` methods.
=> Add more ref tests

azure-devops/azext_devops/dev/repos/ref.py
- [NA] : This PR has a corresponding issue open in the Repository.
- [NA] : Approach is signed off on the issue.
=> Minor fix - include the models from compressed package

doc/samples.md
=> Updating docs to fix login steps

.vscode/launch.json, .vscode/tasks.json, scripts/dev_setup.py, scripts/run_az.py
=> Support debugging from VSCode

.vscode/settings.json, azure-devops/azext_devops/test/common/_init_.py, azure-devops/azext_devops/test/team/_init_.py
I was able to debug UTs using this but not the Live tests.
The __init__ file changes are because the files were incorrect and that was impacting module discovery
=> Changes to enable test discovery + running + debugging from VSCode

.vscode/tasks.json
Post this change on using this repo in VSCode and using "Ctrl + Shift + B" users will get 3 options
1. Uninstall extension
2. Install extension
3. Update extension
so this just for productivity in development 
Tested on windows and linux (because paths are involved)
=> Build tasks in VSCode for install/ uninstall and update of extension

azure-devops/azext_devops/dev/pipelines/runs.py
=> Minor help text fix in pipelines runs artifact list command

azure-devops/azext_devops/dev/team/user.py, azure-devops/azext_devops/test/team/test_user.py, tests/test_devopsUserTest.py
=> Argument rename for user add command and help text fixes

azure-devops/azext_devops/test/artifacts/test_univeral.py, azure-devops/azext_devops/test/boards/test_workitem.py, azure-devops/azext_devops/test/pipelines/test_pipelines_build.py, azure-devops/azext_devops/test/repos/test_policy.py, azure-devops/azext_devops/test/repos/test_pull_request.py, azure-devops/azext_devops/test/repos/test_ref.py, azure-devops/azext_devops/test/repos/test_repository.py, azure-devops/azext_devops/test/team/test_extension.py, azure-devops/azext_devops/test/team/test_service_endpoint.py, azure-devops/azext_devops/test/team/test_team.py, azure-devops/azext_devops/test/team/test_user.py, azure-devops/azext_devops/test/utils/authentication.py, azure-devops/azext_devops/test/utils/helper.py
=> Refactoring authentication code for UTs

azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/test/team/test_service_endpoint.py
=> fix typo in azure_rm_service_principal parameter 

azure-devops/azext_devops/dev/admin/banner.py, azure-devops/azext_devops/dev/pipelines/runs.py, azure-devops/azext_devops/dev/repos/commands.py, azure-devops/azext_devops/dev/repos/ref.py, azure-devops/azext_devops/dev/team/team.py
=> Cleanup related to unrequired code

azure-devops/azext_devops/dev/repos/policy.py
=> fix link to policy doc

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, azure-devops/azext_devops/dev/boards/work_item.py, azure-devops/azext_devops/dev/common/arguments.py, azure-devops/azext_devops/dev/common/artifacttool.py, azure-devops/azext_devops/dev/common/artifacttool_updater.py, azure-devops/azext_devops/dev/common/credential_store.py, azure-devops/azext_devops/dev/common/exception_handler.py, azure-devops/azext_devops/dev/common/git.py, azure-devops/azext_devops/dev/common/identities.py, azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/dev/common/telemetry.py, azure-devops/azext_devops/dev/common/vsts_git_url_info.py, azure-devops/azext_devops/dev/pipelines/build_definition.py, azure-devops/azext_devops/dev/pipelines/release_definition.py, azure-devops/azext_devops/dev/team/project.py, scripts/runStyleCheck.ps1
Main intent of this change is 
1. To make sure developers can run this locally (assuming most of the devs will have latest python on their devloper box)
2. Benefit from the latest pylint rules
https://github.com/Microsoft/azure-devops-cli-extension/issues/441
=> Upgrade pylint to work with latest python version

azure-devops/azext_devops/dev/repos/_format.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/pull_request.py
=> Ability to create draft PRs

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, doc/samples.md
View the updated samples.md @ 
https://github.com/gauravsaralMs/azure-devops-cli-extension/blob/users/gsaral/marldownlinting/doc/samples.md
=> add steps in PR and merge for checking markdown lint issues

azure-devops/azext_devops/dev/common/exception_handler.py, azure-devops/azext_devops/dev/pipelines/build.py, scripts/backCompatChecker.py
Issues: 
1. Remove  Obsolete parameter.
1. Getting stack trace when skipping compulsory params eg az pipelines build queue , az pipelines release create
=> Minor bug fixes from the bash

azure-devops/azext_devops/dev/repos/repository.py
=> Changes to remove type and rtype from comment

.azure-pipelines/templates/build-publish-azure-devops-cli-extension.yml, scripts/removeComments.py
This change reduces the final whl size from ~14 MB to ~7MB so we should be saving good time in download
=> script to remove comments from sdk file before creating wheel

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, doc/samples.md
=> Update python version on agent since 3.7.0 is not available

azure-devops/azext_devops/dev/boards/_format.py
=> Fix in work item table response for client v5.0

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> Fix python versions in Mac machines

azure-devops/azext_devops/dev/pipelines/_format.py, azure-devops/azext_devops/dev/pipelines/_help.py, azure-devops/azext_devops/dev/pipelines/arguments.py, azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/pipelines/pipeline.py, azure-devops/azext_devops/dev/pipelines/pipeline_run.py
Partial commands for #333 Create and update pipeline will be taken in separate PR. 
Fixing the issue #465 reported for build list in the new pipeline runs list command.
=> Pipelines commands ported to new naming and some add ons

azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/pull_request.py
More details on three state flags [here](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#registering-flags).
=> Use three state flags for boolean values like draft in create and update PR

azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/pull_request.py
=> PR create update command change bool types from str in update

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, doc/samples.md
=> update python version to use 3.x

azure-devops/azext_devops/dev/boards/arguments.py, azure-devops/azext_devops/dev/boards/relations.py
=> Work Item relation minor fixes

azure-devops/azext_devops/dev/team/_help.py
=> remove help text from security

azure-devops/azext_devops/dev/repos/policy.py, azure-devops/azext_devops/test/repos/test_policy.py
Addresses issue: https://github.com/Azure/azure-devops-cli-extension/issues/563
=> add branch_match_type in missing policies

azure-devops/azext_devops/dev/common/github_credential_manager.py, azure-devops/azext_devops/dev/common/prompting.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/azure_repos_helper.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/github_api_helper.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/pipelines_resource_provider.py
=> Pipelines feedback comments 

azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/dev/team/commands.py
This reverts commit d7197f2fd21d6db59db03ebc15bab182f6ff2af7.
=> Enabling security group commands again

azure-devops/azext_devops/dev/team/_help.py
=> fix example text for release

.azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, .azure-pipelines/templates/install-azure-cli-edge.yml, .azure-pipelines/templates/install-azure-cli-released.yml, .azure-pipelines/templates/run-tests.yml
=> Temp, run tests with released Azure CLI (also run one step which will always run with released Azure CLI)

.azure-pipelines/azure-pipelines-merge.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/version.py
=> Upgrade version to 0.8.0

.azure-pipelines/azure-pipelines-merge.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Increment version for next release

doc/release_new_version.md
=> Fix pipeline links

azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/pipelines/runs_artifacts.py, azure-devops/azext_devops/test/pipelines/test_pipeline_runs_artifacts.py
=> Fix issue for artifacts list and add tests

azure-devops/azext_devops/dev/repos/pull_request.py
=> Pull request completion not working due to bypass policy 

examples/createWorkitemsInBulk.md
Check the file here - https://github.com/Azure/azure-devops-cli-extension/blob/ExampleReadme/examples/createWorkitemsInBulk.md
=> Create Readme file for Bulk workitem script

examples/Utils/UtilityHelper.ps1, examples/markStaleWorkItem.md, examples/markStaleWorkItem.ps1
=> Add Script for marking untouched/ old work items as stale

azure-devops/azext_devops/dev/artifacts/universal.py, azure-devops/azext_devops/dev/common/artifacttool.py, azure-devops/azext_devops/test/artifacts/test_univeral.py
=> add support for upack download filter

azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/extension.py, scripts/backCompatChecker.py
Fixes : https://github.com/Azure/azure-devops-cli-extension/issues/595
=> Fix param names in extension commands

examples/PRReviewReminder.md, examples/PRReviewReminder.ps1
=> adding script in example which can be used for PR review reminder

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/commands.py, azure-devops/azext_devops/dev/repos/pull_request.py, azure-devops/azext_devops/test/repos/test_pull_request.py, tests/test_reposPrCommandsReviewersTest.py
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/604
=> Merge PR status update commands with pr update commands

azure-devops/azext_devops/dev/team/commands.py, azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/devops_sdk/v5_0/service_endpoint/service_endpoint_client.py, azure-devops/azext_devops/test/team/test_service_endpoint.py
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/609
=> changes for deleting service-endpoint

azure-devops/azext_devops/dev/pipelines/_help.py, azure-devops/azext_devops/dev/pipelines/pipeline.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py, azure-devops/azext_devops/dev/pipelines/pipeline_run.py, azure-devops/azext_devops/dev/pipelines/runs_artifacts.py, azure-devops/azext_devops/dev/team/security_permission.py, azure-devops/azext_devops/dev/team/service_endpoint.py
IMO, we should add preview to service endpoint create command because we would have to break it at some point of time 
cc: @snankani  @geverghe 
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/603
=> add (PREVIEW) to pipeline and security commands

azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/test/team/test_service_endpoint.py
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/618
=> Do not take credentials from arguments in service endpoint creation

azure-devops/azext_devops/azext_metadata.json
=> remove preview from extension metadata

azure-devops/azext_devops/dev/pipelines/build.py
=> Allow specifying queue id when queuing a build

azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/configure.py, azure-devops/azext_devops/dev/team/extension.py, azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/dev/team/user.py
=> Bug Fixes around three state flags

azure-devops/azext_devops/test/artifacts/test_univeral.py, azure-devops/azext_devops/test/boards/test_workitem.py, azure-devops/azext_devops/test/common/test_services.py, azure-devops/azext_devops/test/repos/test_import_request.py, azure-devops/azext_devops/test/repos/test_policy.py, azure-devops/azext_devops/test/repos/test_pull_request.py, azure-devops/azext_devops/test/repos/test_ref.py, azure-devops/azext_devops/test/repos/test_repository.py, azure-devops/azext_devops/test/team/test_extension.py, azure-devops/azext_devops/test/team/test_security_group.py, azure-devops/azext_devops/test/team/test_security_permission.py, azure-devops/azext_devops/test/team/test_team.py, azure-devops/azext_devops/test/team/test_user.py
=> Remove detect off from Unit tests

README.md
=> Update output of devops -h in readme.md (this was outdated)

azure-devops/azext_devops/dev/common/utils.py, azure-devops/azext_devops/dev/team/feedback.py
=> Open the issues page for feedback instead of just posting the link

azure-devops/azext_devops/dev/common/utils.py, azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/invoke.py, azure-devops/azext_devops/dev/team/wiki.py
=> Adding encoding parameter to allow non ascii encoded files to be allowed

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
Fixes build failures in PR and CI runs due python version on agent being updated to 2.7.16
=> Fix python 2 version availability

examples/Scaffolding/scaffolding.md
=> Including Scaffolding readme updates

azure-devops/azext_devops/dev/artifacts/universal.py, azure-devops/azext_devops/dev/common/artifacttool.py
=> Universal package file filter name change and extra validation

.azure-pipelines/azure-pipelines-merge.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Version bump to 0.10.0

azure-devops/azext_devops/dev/common/prompting.py
I have implemented a pagination list also but during the testing I figured out the exact issue for long list failing was the deinit missing. 
Tested using -https://github.com/atbagga/PythonSamples/blob/237be053766d8842b7cf1dd054777fbc41618cf0/prompting.py#L4-L11
=> Fixing long list issue

azure-devops/azext_devops/dev/artifacts/universal.py
=> Fix pylint for help text

doc/samples.md
`az pipelines build show --build-id 1 --open` should change to `az pipelines build show --id 1 --open`. This fixes #653
=> Update samples.md for az pipelines build show 

azure-devops/azext_devops/dev/pipelines/agent_pool_queue.py, azure-devops/azext_devops/test/pipelines/test_pipeline_agents.py
Remove properties from the pool management commands.
=> Remove properties from the pool management commands.

azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/pipelines_resource_provider.py
=> Fix polling spinner on windows

azure-devops/azext_devops/dev/boards/_help.py
=> Help text example fix

.azure-pipelines/azure-pipelines-merge.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/dev/boards/_help.py, azure-devops/azext_devops/version.py
=> Increment version to 0.12.0

azure-devops/azext_devops/dev/artifacts/universal.py
=> Remove Universal Packages preview message

.azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-released-version.yml
=> Schedule pipeline run through YAML

.azure-pipelines/azure-pipelines-released-version.yml
=> Schedule pipeline in release branch

azure-devops/azext_devops/dev/artifacts/_help.py, azure-devops/azext_devops/dev/artifacts/universal.py
=> Universal commands - Remove preview message

azure-devops/azext_devops/dev/pipelines/pipeline_run.py, azure-devops/azext_devops/dev/repos/ref.py, azure-devops/azext_devops/dev/team/arguments.py
Fixes https://github.com/Azure/azure-cli-extensions/issues/776
=> Help text changes for organization and project

azure-devops/azext_devops/dev/boards/_format.py
=> Fix table output for workitem query output

doc/samples.md
Reference Issues - #692 , #518
=> Fix Samples.md with correct usage of PAT in Azure Pipelines

examples/Scaffolding/Boards/boardsettings.ps1, examples/Scaffolding/Repos/setPolicies.ps1, examples/Scaffolding/scaffolding.ps1
=> Update scaffolding scripts to include Boards commands

README.md, doc/samples.md
Fixing the links to documentation page and including notice in samples for non-maintenance moving forward.
=> Including documentation link fixes

azure-devops/azext_devops/dev/team/credentials.py
=> Login help text edited to add PAT login help documentation.

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, scripts/backCompatChecker.py
=> enable back compat tests

azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/pipelines_resource_provider.py
=> Fix rename in pipeline kubernetes connection API

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/templates/download-install-local-azure-devops-cli-extension.yml, .azure-pipelines/templates/run-tests.yml
=> attempt to delete extension dir

azure-devops/azext_devops/dev/common/git.py, azure-devops/azext_devops/dev/pipelines/build.py, azure-devops/azext_devops/dev/pipelines/pipeline.py
=> Allow queueing of builds/pipelines with PR branches

azure-devops/azext_devops/dev/pipelines/_format.py, azure-devops/azext_devops/dev/pipelines/arguments.py, azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py
=> Pipeline create command should have an option to skip the first run

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Increment release version to 0.13.0

azure-devops/azext_devops/dev/boards/iteration.py, tests/recordings/test_boards_iterations.yaml
=> Fix boards iteration error handling - API error message has changed 

.azure-pipelines/azure-pipelines-released-version.yml
=> Schedule run for released version

README.md, azure-devops/azext_devops/azext_metadata.json, azure-devops/azext_devops/dev/boards/_help.py, azure-devops/azext_devops/dev/boards/area.py, azure-devops/azext_devops/dev/boards/commands.py, azure-devops/azext_devops/dev/boards/iteration.py, azure-devops/azext_devops/dev/pipelines/_help.py, azure-devops/azext_devops/dev/pipelines/agent_pool_queue.py, azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/pipelines/pipeline.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py, azure-devops/azext_devops/dev/pipelines/pipeline_run.py, azure-devops/azext_devops/dev/pipelines/pipeline_variables.py, azure-devops/azext_devops/dev/pipelines/runs_artifacts.py, azure-devops/azext_devops/dev/pipelines/variable_group.py, azure-devops/azext_devops/dev/team/commands.py, azure-devops/azext_devops/dev/team/security_permission.py, azure-devops/azext_devops/dev/team/service_endpoint.py, tests/recordings/test_boards_iterations.yaml
=> [Az CLI Min Version Updated] Mark Preview using new Knack feature

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> Enable back compat broken tests

azure-devops/azext_devops/dev/common/exception_handler.py
Fixes: https://github.com/Azure/azure-devops-cli-extension/issues/759
=> handle AzureDevOpsAuthenticationError and raise CLIError for the same

azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/policy.py, tests/recordings/test_repos_policies_createUpdateShowListDelete.yaml, tests/test_reposPoliciesTest.py
=> Allow other merge type policies in the repos policy command

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> Enable back ubuntu runs

doc/command_mapping.md
=> Fix az repos pr command mapping

tests/test_adminBannerTest.py, tests/test_boardsAreaTest.py, tests/test_boardsIterationTest.py, tests/test_boardsQueryTest.py, tests/test_boardsRelationTest.py, tests/test_boardsWorkItemTest.py, tests/test_devopsProjectTest.py, tests/test_devopsSecurityGroupTest.py, tests/test_devopsSecurityPermissionTest.py, tests/test_devopsTeamTest.py, tests/test_devopsUserTest.py, tests/test_extensionSearch.py, tests/test_gitAliasTest.py, tests/test_invoke.py, tests/test_pipelineAgentPoolQueueTest.py, tests/test_pipelinesBuildDefinitionsTest.py, tests/test_pipelinesBuildTagTest.py, tests/test_pipelinesBuildTest.py, tests/test_pipelinesCreateAndVariablesTest.py, tests/test_reposImportTest.py, tests/test_reposPoliciesTest.py, tests/test_reposPrCommandsReviewersTest.py, tests/test_reposPrPoliciesWorkItemsTest.py, tests/test_reposRefTest.py, tests/test_reposRepoTest.py, tests/test_variableGroup.py, tests/test_wikiAndPagesTest.py, tests/utilities/helper.py
=> Optimise test runs in recording mode to skip sleep

azure-devops/azext_devops/dev/artifacts/universal.py, azure-devops/azext_devops/dev/common/artifacttool.py
This reverts commit 09f996cacd211274be0d6475f5f058782068c67c.
=> Revert - Adding optional project parameter to artifacts universal commands (#785)

azure-devops/azext_devops/dev/common/git.py, azure-devops/azext_devops/dev/pipelines/_format.py, azure-devops/azext_devops/dev/pipelines/_help.py, azure-devops/azext_devops/dev/pipelines/build_definition.py, azure-devops/azext_devops/dev/pipelines/commands.py, azure-devops/azext_devops/dev/pipelines/pipeline_run.py, azure-devops/azext_devops/dev/repos/arguments.py, pylintrc
=> Minor fixes from bug bash

azure-devops/azext_devops/dev/pipelines/arguments.py, azure-devops/azext_devops/dev/pipelines/build_definition.py, azure-devops/azext_devops/dev/pipelines/pipeline_create.py, azure-devops/azext_devops/dev/repos/arguments.py, azure-devops/azext_devops/dev/repos/policy.py, scripts/backCompatChecker.py
=> Hide the deprecated options.

azure-devops/azext_devops/dev/artifacts/_help.py, azure-devops/azext_devops/dev/boards/_help.py, azure-devops/azext_devops/dev/pipelines/_help.py, azure-devops/azext_devops/dev/repos/_help.py
Fixes: https://github.com/Azure/azure-cli-extensions/issues/976
=> Help text changes to fix documentation

tests/test_devopsSecurityGroupTest.py
=> Fix flaky live test

scripts/backCompatChecker.py
=> Fix merge pipeline failure and improve debugging of backCompat script

azure-devops/azext_devops/dev/team/_help.py
=> Documentation fix for service endpoint commands

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, doc/samples.md
=> use python 3.7 instead of latest because 3.8 has issues

azure-devops/azext_devops/dev/team/credentials.py
=> Gracefully fail while keyring faults and give user warning to use environment variable

azure-devops/azext_devops/dev/team/_help.py, azure-devops/azext_devops/dev/team/service_endpoint.py
=> Replace generic link with sectional links

azure-devops/azext_devops/dev/common/vsts_git_url_info.py
=> Fix detect issue for no code read permission

azure-devops/azext_devops/dev/admin/banner.py, scripts/backCompatChecker.py, tests/test_adminBannerTest.py
=> Handle empty expiration date and make id required in admin banner update cmd

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Moving to next release : 0.15.0

azure-devops/azext_devops/dev/team/credentials.py, azure-devops/azext_devops/test/team/test_login.py
=> Fix regression and add tests 

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> Re-enable tests

.azure-pipelines/templates/setup-ci-machine.yml
=> Fix pipelines break [release branch]

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Release version increment 0.16.0

doc/release_new_version.md
=> Adding step in release new version to fix released version pipeline

azure-devops/azext_devops/dev/team/_format.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/extension.py, scripts/backCompatChecker.py
Fixes #825
1. Extension install/uninstall/enable/disable/show 
- Renamed extension-name to extension-id
-  Renamed publisher-name to publisher-id
2. Extension search command
- Changed table output from extension-id to extension-name
- Changed table output from publisher-id to publisher-name
3. Help text update to stitch search->install scenario
=> [Breaking change] Devops Org Extension parameter rename for extension management and search command

doc/dev_setup.md
=> Fixing Dev setup instructions

azure-devops/azext_devops/dev/repos/policy.py
=> Fix request values for Repo merge strategy policy

azure-devops/azext_devops/dev/team/_format.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/commands.py, azure-devops/azext_devops/dev/team/service_endpoint.py, azure-devops/azext_devops/test/team/test_service_endpoint.py
=> Service Endpoint update command to set pipeline access property

azure-devops/azext_devops/dev/team/_help.py
=> Update help text

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Release version increment to 0.17.0

azure-devops/azext_devops/dev/team/security_group.py
=> Update help for group membership add

azure-devops/azext_devops/dev/team/credentials.py
=> Fix for not pasting the token

azure-devops/azext_devops/dev/team/credentials.py
=> Users/mitsha microsoft/ctrl v issue fix

azure-devops/azext_devops/dev/boards/_help.py, azure-devops/azext_devops/dev/boards/work_item.py
=> Update query help text

.github/CODEOWNERS
=> Removing myself from Codeowners

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, azure-devops/azext_devops/dev/common/artifacttool_updater.py, azure-devops/azext_devops/dev/common/external_tool.py, azure-devops/azext_devops/dev/pipelines/pipeline_create_helpers/pipelines_resource_provider.py, azure-devops/azext_devops/dev/repos/import_request.py, azure-devops/setup.py, doc/dev_setup.md, doc/samples.md
=> Remove python 2.7 support

.azure-pipelines/azure-pipelines-pr.yml, azure-devops/azext_devops/azext_metadata.json, azure-devops/azext_devops/dev/common/telemetry.py
=> Telemetry Bug Fix

azure-devops/azext_devops/dev/repos/policy.py
=> Fix for the case-enforcement policy creation

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
Updating the Release Version to 0.19.0
=> Incrementing Release to v0.19.0

azure-devops/azext_devops/dev/common/git.py, azure-devops/azext_devops/dev/pipelines/build.py, azure-devops/azext_devops/dev/pipelines/pipeline.py
=> Allow az pipeline run to specify git tag as branch param

azure-devops/azext_devops/dev/common/artifacttool.py, azure-devops/azext_devops/dev/common/external_tool.py, scripts/runStyleCheck.ps1
Commented out a raise to allow wait() to run and raise CLI error with exit code
Fix pylint version to avoid style check issues.
=> Zhentan exitcode

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/templates/install-azure-cli-edge.yml, azure-devops/azext_devops/dev/pipelines/pipeline_create.py
=> Updating pipeline_create to address test failure.

.azure-pipelines/azure-pipelines-merge.yml
Addressing 'Azure DevOps CLI - Merge GitHub' pipeline run failure - https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=130257&view=logs&j=607b5b45-2d3b-5f3c-697b-70570d59f78a&t=e4947a12-e368-5542-5727-6c69943f273b.
=> Fixing merge pipeline failure.

.azure-pipelines/azure-pipelines-merge.yml
Addressing parse error in merge pipeline.
=> Addressing YAML parse error for merge pipeline.

.azure-pipelines/azure-pipelines-create-release.yml
Updating service connection to address issue in release pipeline - https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=130276&view=logs&j=516a99d3-db7c-5136-ef8c-05c63e967392&t=2015a970-7918-5463-6f0f-388000cd53fc
=> Updating service connection in release pipeline.

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .github/ISSUE_TEMPLATE/bug_report.md, .vscode/tasks.json, azure-devops/azext_devops/version.py
Updated version references to support new version - https://github.com/Azure/azure-devops-cli-extension/pull/980/files
=> Updating version references.

.github/stale.yml
after 1 day, close the github issue and comment to redirect user to ADO dev community.
=> implement probot stale

azure-devops/azext_devops/dev/boards/work_item.py
Fixes https://github.com/Azure/azure-devops-cli-extension/issues/1134
=> Adding example for multiple fields command for az boards work-item create

azure-devops/azext_devops/dev/pipelines/pipeline_run.py
Fixes: #1113 
Code change not needed for the issue
Help text updated for the command
```
:param pipeline_ids: IDs (space separated) of definitions to list builds for.
For multiple pipeline ids:  --pipeline-ids 1 2
:type pipeline_ids: list of int
```
=> Example in help changed for command

README.md
Fixes: #1116 
No code changes needed for this as well
Read me changes done as requested
=> Reference url chagned

azure-devops/azext_devops/dev/common/services.py, azure-devops/azext_devops/test/common/test_services.py
Fixes: #1151 
To show the warning message code resolves the organization URL.
the resolved URL is then compared with the know patterns.
https://dev.azure.com/*
*.visualstudio.com
If URL does not matches with know patterns the warning message is shown
=> Added warning message while using the commands with ADO server

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Version changed After release 0.20.0

.azure-pipelines/azure-pipelines-create-release.yml, .azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/azure-pipelines-released-version.yml, doc/samples.md
Fixes: #1164 
Changes vmimage from ubuntu-16.04 to ubuntu-latest for pipelines
=> VM image changed for pipeline

tests/recordings/test_boards_releations_create_remove.yaml, tests/test_boardsRelationTest.py
Fixes: #1195 
Changed the organization
Changed the Issue type to **Task** instead of **Bug**, as default project type is **Basic** which do not have the bug.
=> validate_relation_count_on_work_item fixed

tests/recordings/test_devops_group_and_member_tests.yaml, tests/test_devopsSecurityGroupTest.py
increased attempt count
Fixes: #1174
=> Fixed test_devops_group_and_member_tests

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Release and version number updated After 0.22.0

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Release and version number updated

.azure-pipelines/templates/setup-ci-machine.yml
=> install azure-devtools explicitly in setup ci machine

.github/CODEOWNERS
=> add aasiddiq as code owner

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Post release 23

.vscode/launch.json
=> launch.json changes reverted

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/launch.json, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Post Realse 24

azure-devops/azext_devops/dev/team/project.py
=> Test CLI Release

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py, doc/authoring_tests.md
=> PostRelease25

SECURITY.md
=> Update to fix markdown SECURITY.md build errors

.azure-pipelines/azure-pipelines-create-release.yml
There is no open issue . This is a change to refer to correct endpoint as the person / account who owned previous service endpoint has left rendering the endpoint unauthorized.
=> Updated yaml to reflect correct service endpoint

azure-devops/azext_devops/dev/repos/arguments.py
Update argument text message. Fixes GitHub Issue - [24172]( https://github.com/Azure/azure-cli/issues/24172)
=> Update argument text message

.azure-pipelines/azure-pipelines-live-test-run.yml, .azure-pipelines/azure-pipelines-merge.yml, .github/CODEOWNERS
=> versionIncompatabilitychanges

.azure-pipelines/azure-pipelines-live-test-run.yml
=> pipelinechanges

.azure-pipelines/azure-pipelines-live-test-run.yml
=> RunLiveTestTaskCommented

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml
=> PostReleaseChanges

azure-devops/azext_devops/dev/pipelines/pipeline_run.py
=> Corrected the spelling of Separated

azure-devops/azext_devops/dev/repos/pull_request.py
Related issue: #1357
---
This implementation of the --labels parameter works with space separated labels.
example:
```powershell
az repos pr create `
--labels "documentation automated"
```
=> Added `--labels` parameter to `az repos pr create`

.azure-pipelines/azure-pipelines-pr.yml, azure-devops/azext_devops/dev/repos/pull_request.py
=> Added install Setup tools Task

.azure-pipelines/azure-pipelines-merge.yml
=> macimagechanges

.azure-pipelines/azure-pipelines-merge.yml
=> Users/v anvashist/mergechanges

.azure-pipelines/azure-pipelines-live-test-run.yml
=> commenting the Live test run Task due to test fail blocker.

.vscode/tasks.json, azure-devops/azext_devops/version.py
=> missed post release changes for previous release

.vscode/tasks.json, azure-devops/azext_devops/version.py
=> changing the version from 0.27.0 to 1.0.0

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> post release changes 1.0.1

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
Reverts Azure/azure-devops-cli-extension#1406
=> Revert "post release changes 1.0.1"

.azure-pipelines/azure-pipelines-merge.yml, .azure-pipelines/azure-pipelines-pr.yml, .azure-pipelines/templates/run-tests.yml, .vscode/tasks.json, azure-devops/azext_devops/version.py
=> Post Release Changes

.azure-pipelines/azure-pipelines-create-release.yml
=> Added New service connection

.github/actions/build-publish-azure-cli-test-sdk/action.yml, .github/actions/build-publish-azure-devops-cli-extension/action.yml, .github/actions/download-install-local-azure-devops-cli-extension-with-pip/action.yml, .github/actions/download-install-local-azure-devops-cli-extension/action.yml, .github/actions/download-install-local-azure-test-sdk/action.yml, .github/actions/install-azure-cli-edge/action.yml, .github/actions/install-azure-cli-released/action.yml, .github/actions/run-tests/action.yml, .github/actions/setup-ci-machine/action.yml, .github/workflows/pr-workflow.yml, pylintrc, scripts/runStyleCheck.ps1
=> Pr workflow migration changes

.github/workflows/merge-workflow.yml
=> Merge workflow changes

.github/workflows/released-version.yml
=> fixed syntax issue on line no 32

.azure-pipelines/azure-pipelines-create-release.yml
=> create release yml fixes

.azure-pipelines/azure-pipelines-create-release-old.yml
=> adding the old file without any changes

azure-devops/azext_devops/dev/repos/_help.py, azure-devops/azext_devops/dev/team/arguments.py, azure-devops/azext_devops/dev/team/configure.py, azure-devops/azext_devops/dev/team/credentials.py, azure-devops/azext_devops/dev/team/service_endpoint.py, doc/getting_started.md
=> Fixing lint errors
